### ISSUE TITLE
User menu

### ISSUE THREAD

**Issue by iangilman** [ContextInstitute/bfcom#31]
I figure rather than continuing to discuss in the pull request #21, we should start a new thread in this issue. See #21 for the discussion so far. 

@DavidScottBernstein this seems like something for you to tackle after #30. No rush here... just lining things up for the future.

**Comment by DavidScottBernstein** [comment]
@rgilman There was a mention in #21 of adding styles that the other Robert created to the flyout User menu. I’m using Foundations dropdown-pane, which has lots of functionality but I’m not sure how to inherit those styles and then apply our additional styles. Your comment in #21 suggests we use .user-dropdown but so far, I’ve only been able to make it work with dropdown-pane. Suggestions?

**Comment by rgilman** [comment]
@DavidScottBernstein, that's great! Stick with Foundation. I would like us to use Foundation components _wherever_ they are useful rather than rolling our own. (The one exception is I want us to use CSS Grid instead of Foundation Grid - see #38.)

When Robert West did that work we were using a different starter theme that didn't have Foundation.

**Comment by iangilman** [comment]
Fixed by #39.
